/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.senai.sp.jandira.ui;

import br.senai.sp.jandira.dao.EspecialidadeDAO;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 22282168
 */
public class EspecialidadesPanel extends javax.swing.JPanel {

    /**
     * Creates new form EspecialidadesPanel
     */
    public EspecialidadesPanel() {
        initComponents();
        EspecialidadeDAO.criarListaDeEspecialidade();
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonAtualizar = new javax.swing.JButton();
        buttonEditar = new javax.swing.JButton();
        buttonApagar = new javax.swing.JButton();
        scroolEspecilidades = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Especialidades"));
        setPreferredSize(new java.awt.Dimension(800, 330));
        setLayout(null);

        buttonAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/atualizar (1).png"))); // NOI18N
        buttonAtualizar.setToolTipText("Atualizar");
        add(buttonAtualizar);
        buttonAtualizar.setBounds(610, 250, 70, 70);

        buttonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/escrevendo.png"))); // NOI18N
        buttonEditar.setToolTipText("Editar");
        add(buttonEditar);
        buttonEditar.setBounds(690, 250, 70, 70);

        buttonApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/lixeira-de-reciclagem.png"))); // NOI18N
        buttonApagar.setToolTipText("Apagar");
        buttonApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonApagarActionPerformed(evt);
            }
        });
        add(buttonApagar);
        buttonApagar.setBounds(530, 250, 70, 70);

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scroolEspecilidades.setViewportView(jTable1);

        add(scroolEspecilidades);
        scroolEspecilidades.setBounds(40, 20, 710, 220);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonApagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonApagarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonApagar;
    private javax.swing.JButton buttonAtualizar;
    private javax.swing.JButton buttonEditar;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane scroolEspecilidades;
    // End of variables declaration//GEN-END:variables

private void preencherTabela() {
 
       jTable1.setModel(EspecialidadeDAO.getEspecialidadesModel());
   }




}
