/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.senai.sp.jandira.ui;

import java.awt.Toolkit;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 22282168
 */
public class HomeFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeFrame
     */
    public HomeFrame() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/br/senai/sp/jandira/img/entrega-agendada.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelSistemaAgendas = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        buttonMedico = new javax.swing.JButton();
        buttonAgenda = new javax.swing.JButton();
        buttonEspecialidades = new javax.swing.JButton();
        buttonPaciente = new javax.swing.JButton();
        buttonPlanoSaude = new javax.swing.JButton();
        buttonSairEspecialidades = new javax.swing.JButton();
        panelEspecialidades = new javax.swing.JPanel();
        labelEspecialidades = new javax.swing.JLabel();
        separatorEspecialidades = new javax.swing.JSeparator();
        scroolEspecilidades = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonApagar = new javax.swing.JButton();
        buttonAtualizar = new javax.swing.JButton();
        buttonEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Agendamentos");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setLayout(null);

        labelSistemaAgendas.setBackground(new java.awt.Color(0, 0, 0));
        labelSistemaAgendas.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        labelSistemaAgendas.setForeground(new java.awt.Color(102, 102, 102));
        labelSistemaAgendas.setText("Sistema de Agendamento de Consulta");
        jPanel1.add(labelSistemaAgendas);
        labelSistemaAgendas.setBounds(230, 30, 500, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/registo-medico (3).png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 0, 64, 70);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 930, 80);

        buttonMedico.setBackground(new java.awt.Color(102, 102, 102));
        buttonMedico.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        buttonMedico.setForeground(new java.awt.Color(255, 255, 255));
        buttonMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/equipe-medica (1).png"))); // NOI18N
        buttonMedico.setText("Médicos");
        buttonMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMedicoActionPerformed(evt);
            }
        });
        getContentPane().add(buttonMedico);
        buttonMedico.setBounds(290, 120, 120, 40);

        buttonAgenda.setBackground(new java.awt.Color(102, 102, 102));
        buttonAgenda.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        buttonAgenda.setForeground(new java.awt.Color(255, 255, 255));
        buttonAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/entrega-agendada.png"))); // NOI18N
        buttonAgenda.setText("Agenda");
        buttonAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAgendaActionPerformed(evt);
            }
        });
        getContentPane().add(buttonAgenda);
        buttonAgenda.setBounds(40, 120, 110, 40);

        buttonEspecialidades.setBackground(new java.awt.Color(102, 102, 102));
        buttonEspecialidades.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        buttonEspecialidades.setForeground(new java.awt.Color(255, 255, 255));
        buttonEspecialidades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/apresentacao.png"))); // NOI18N
        buttonEspecialidades.setText("Especialidades");
        buttonEspecialidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEspecialidadesActionPerformed(evt);
            }
        });
        getContentPane().add(buttonEspecialidades);
        buttonEspecialidades.setBounds(430, 120, 150, 40);

        buttonPaciente.setBackground(new java.awt.Color(102, 102, 102));
        buttonPaciente.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        buttonPaciente.setForeground(new java.awt.Color(255, 255, 255));
        buttonPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/paciente (1).png"))); // NOI18N
        buttonPaciente.setText("Paciente");
        buttonPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(buttonPaciente);
        buttonPaciente.setBounds(160, 120, 120, 40);

        buttonPlanoSaude.setBackground(new java.awt.Color(102, 102, 102));
        buttonPlanoSaude.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        buttonPlanoSaude.setForeground(new java.awt.Color(255, 255, 255));
        buttonPlanoSaude.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/plano-de-saude.png"))); // NOI18N
        buttonPlanoSaude.setText("Plano de Saúde");
        buttonPlanoSaude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPlanoSaudeActionPerformed(evt);
            }
        });
        getContentPane().add(buttonPlanoSaude);
        buttonPlanoSaude.setBounds(600, 120, 160, 40);

        buttonSairEspecialidades.setBackground(new java.awt.Color(255, 0, 0));
        buttonSairEspecialidades.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        buttonSairEspecialidades.setForeground(new java.awt.Color(255, 255, 255));
        buttonSairEspecialidades.setText("SAIR");
        getContentPane().add(buttonSairEspecialidades);
        buttonSairEspecialidades.setBounds(830, 100, 80, 60);

        panelEspecialidades.setBackground(new java.awt.Color(204, 204, 204));
        panelEspecialidades.setForeground(new java.awt.Color(255, 255, 255));
        panelEspecialidades.setLayout(null);

        labelEspecialidades.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        labelEspecialidades.setForeground(new java.awt.Color(0, 0, 0));
        labelEspecialidades.setText("Lista de Especialidades:");
        panelEspecialidades.add(labelEspecialidades);
        labelEspecialidades.setBounds(10, 15, 130, 10);
        panelEspecialidades.add(separatorEspecialidades);
        separatorEspecialidades.setBounds(140, 20, 640, 10);

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scroolEspecilidades.setViewportView(jTable1);

        panelEspecialidades.add(scroolEspecilidades);
        scroolEspecilidades.setBounds(50, 50, 710, 220);

        getContentPane().add(panelEspecialidades);
        panelEspecialidades.setBounds(50, 200, 800, 330);

        buttonApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/lixeira-de-reciclagem.png"))); // NOI18N
        buttonApagar.setToolTipText("Apagar");
        buttonApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonApagarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonApagar);
        buttonApagar.setBounds(580, 580, 70, 70);

        buttonAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/atualizar (1).png"))); // NOI18N
        buttonAtualizar.setToolTipText("Atualizar");
        getContentPane().add(buttonAtualizar);
        buttonAtualizar.setBounds(700, 580, 70, 70);

        buttonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/escrevendo.png"))); // NOI18N
        buttonEditar.setToolTipText("Editar");
        getContentPane().add(buttonEditar);
        buttonEditar.setBounds(820, 580, 70, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonMedicoActionPerformed

    private void buttonAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAgendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAgendaActionPerformed

    private void buttonEspecialidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEspecialidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonEspecialidadesActionPerformed

    private void buttonPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonPacienteActionPerformed

    private void buttonApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonApagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonApagarActionPerformed

    private void buttonPlanoSaudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPlanoSaudeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonPlanoSaudeActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAgenda;
    private javax.swing.JButton buttonApagar;
    private javax.swing.JButton buttonAtualizar;
    private javax.swing.JButton buttonEditar;
    private javax.swing.JButton buttonEspecialidades;
    private javax.swing.JButton buttonMedico;
    private javax.swing.JButton buttonPaciente;
    private javax.swing.JButton buttonPlanoSaude;
    private javax.swing.JButton buttonSairEspecialidades;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelEspecialidades;
    private javax.swing.JLabel labelSistemaAgendas;
    private javax.swing.JPanel panelEspecialidades;
    private javax.swing.JScrollPane scroolEspecilidades;
    private javax.swing.JSeparator separatorEspecialidades;
    // End of variables declaration//GEN-END:variables
    
    private void preencherTabela() {
    
        String[][] dados= {
            {"100", "Jandira", "SP"},
            {"200", "Barueri", "SP"},
            {"300", "Itapevi", "SP"},
            {"400", "Cotia", "SP"},
            {"500", "Curitiba", "PR"},
            {"600", "Fortaleza", "CE"},
        
    };
        String[] titulos = {"CÓDIGO", "NOME DA CIDADE", "ESTADO"};
         
        DefaultTableModel modelo = new DefaultTableModel(dados, titulos);
        
       
        
   }
    



}
