/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.senai.sp.jandira.ui;

/**
 *
 * @author 22282168
 */
public class MedicoDialog extends javax.swing.JDialog {

    /**
     * Creates new form MedicooDialog
     */
    public MedicoDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelAdicionar = new javax.swing.JLabel();
        jLabelImg = new javax.swing.JLabel();
        jLabelimg = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelMedico = new javax.swing.JLabel();
        jTextFieldMedico = new javax.swing.JTextField();
        jLabelTelefone = new javax.swing.JLabel();
        jTextFieldTelefone = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelDataNasc = new javax.swing.JLabel();
        jTextFieldDataNasc = new javax.swing.JTextField();
        jLabelCodigo = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabelCRM = new javax.swing.JLabel();
        jTextFieldCRM = new javax.swing.JTextField();
        jLabelListaEspec = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListEspecialidades = new javax.swing.JList<>();
        jLabelEspecMedico = new javax.swing.JLabel();
        jScrollPaneEspecialidadeMedico = new javax.swing.JScrollPane();
        jListEspecialidadeMedico = new javax.swing.JList<>();
        jButtonCancelar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(null);

        jLabelAdicionar.setBackground(new java.awt.Color(153, 0, 153));
        jLabelAdicionar.setFont(new java.awt.Font("Vineta BT", 0, 18)); // NOI18N
        jLabelAdicionar.setForeground(new java.awt.Color(51, 51, 51));
        jLabelAdicionar.setText("MÉDICO - ADICIONAR");
        jPanel1.add(jLabelAdicionar);
        jLabelAdicionar.setBounds(160, 20, 300, 30);

        jLabelImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/equipamento-medico (1).png"))); // NOI18N
        jPanel1.add(jLabelImg);
        jLabelImg.setBounds(60, 10, 50, 50);

        jLabelimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/farmacia.png"))); // NOI18N
        jPanel1.add(jLabelimg);
        jLabelimg.setBounds(550, 10, 73, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 650, 60);

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalhes do(a) médico(a)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.setLayout(null);

        jLabelMedico.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelMedico.setForeground(new java.awt.Color(0, 0, 0));
        jLabelMedico.setText(" Médico(a)");
        jPanel2.add(jLabelMedico);
        jLabelMedico.setBounds(340, 50, 70, 16);

        jTextFieldMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMedicoActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldMedico);
        jTextFieldMedico.setBounds(340, 70, 160, 22);

        jLabelTelefone.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTelefone.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTelefone.setText("Telefone");
        jPanel2.add(jLabelTelefone);
        jLabelTelefone.setBounds(30, 110, 50, 20);

        jTextFieldTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelefoneActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldTelefone);
        jTextFieldTelefone.setBounds(30, 130, 120, 22);

        jLabelEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelEmail.setForeground(new java.awt.Color(0, 0, 0));
        jLabelEmail.setText("Email");
        jPanel2.add(jLabelEmail);
        jLabelEmail.setBounds(180, 110, 50, 16);

        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldEmail);
        jTextFieldEmail.setBounds(180, 130, 160, 22);

        jLabelDataNasc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelDataNasc.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDataNasc.setText("Data de Nascimento");
        jPanel2.add(jLabelDataNasc);
        jLabelDataNasc.setBounds(370, 110, 150, 16);

        jTextFieldDataNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDataNascActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldDataNasc);
        jTextFieldDataNasc.setBounds(370, 130, 150, 22);

        jLabelCodigo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCodigo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCodigo.setText("Código");
        jPanel2.add(jLabelCodigo);
        jLabelCodigo.setBounds(30, 50, 50, 16);

        jTextFieldCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldCodigo);
        jTextFieldCodigo.setBounds(30, 70, 80, 22);

        jLabelCRM.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCRM.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCRM.setText("CRM");
        jPanel2.add(jLabelCRM);
        jLabelCRM.setBounds(170, 50, 50, 16);

        jTextFieldCRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCRMActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldCRM);
        jTextFieldCRM.setBounds(170, 70, 120, 22);

        jLabelListaEspec.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabelListaEspec.setForeground(new java.awt.Color(102, 102, 102));
        jLabelListaEspec.setText("Lista de Especialidades");
        jPanel2.add(jLabelListaEspec);
        jLabelListaEspec.setBounds(50, 180, 170, 17);

        jListEspecialidades.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListEspecialidades);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(50, 210, 160, 146);

        jLabelEspecMedico.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabelEspecMedico.setForeground(new java.awt.Color(102, 102, 102));
        jLabelEspecMedico.setText("Especialidades do(a) médico(a)");
        jPanel2.add(jLabelEspecMedico);
        jLabelEspecMedico.setBounds(320, 180, 210, 17);

        jListEspecialidadeMedico.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneEspecialidadeMedico.setViewportView(jListEspecialidadeMedico);

        jPanel2.add(jScrollPaneEspecialidadeMedico);
        jScrollPaneEspecialidadeMedico.setBounds(340, 210, 160, 146);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(40, 100, 560, 380);

        jButtonCancelar.setBackground(new java.awt.Color(255, 51, 51));
        jButtonCancelar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCancelar.setText("CANCELAR");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar);
        jButtonCancelar.setBounds(330, 510, 100, 23);

        jButtonSalvar.setBackground(new java.awt.Color(255, 255, 102));
        jButtonSalvar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSalvar.setText("SALVAR");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar);
        jButtonSalvar.setBounds(460, 510, 100, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMedicoActionPerformed

    private void jTextFieldTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefoneActionPerformed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jTextFieldDataNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDataNascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDataNascActionPerformed

    private void jTextFieldCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoActionPerformed

    private void jTextFieldCRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCRMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCRMActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedicoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedicoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedicoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedicoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MedicoDialog dialog = new MedicoDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabelAdicionar;
    private javax.swing.JLabel jLabelCRM;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelDataNasc;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEspecMedico;
    private javax.swing.JLabel jLabelImg;
    private javax.swing.JLabel jLabelListaEspec;
    private javax.swing.JLabel jLabelMedico;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JLabel jLabelimg;
    private javax.swing.JList<String> jListEspecialidadeMedico;
    private javax.swing.JList<String> jListEspecialidades;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneEspecialidadeMedico;
    private javax.swing.JTextField jTextFieldCRM;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldDataNasc;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldMedico;
    private javax.swing.JTextField jTextFieldTelefone;
    // End of variables declaration//GEN-END:variables
}
